# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
