# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('wishes_app', '0002_auto_20181022_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='liker',
            field=models.ManyToManyField(related_name='likes', to='users_app.User'),
        ),
    ]
